name: Pull Request

on:
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - '*.md'
      - 'docs/'
      - 'examples/'
      - 'hack/'

jobs:
  operator-pull-request:
    name: Operator Pull Request
#    uses: stakater/.github/.github/workflows/operator_pull_request.yaml@main
    uses: stakater/IPShield/.github/workflows/_pr.yaml@add20e351d9cf115109164acbf1c64fa2cc5d004
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: stakater-user
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
    with:
      GOLANG_VERSION: ~1.21
      DOCKERFILE_PATH: Dockerfile
      GOLANG_CI_LINT_VERSION: v1.53.3
      Run_GOLANG_CI_LINT: false
      RUN_GOLANG_TESTS: false
      OPERATOR_SDK_VERSION: v1.36.1