name: Push

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'docs/'
      - 'examples/'
      - 'hack/'

jobs:
  push-operator:
    name: Push Operator
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
#    uses: stakater/.github/.github/workflows/operator_push.yaml@main
    uses: stakater/IPShield/.github/workflows/_push.yaml@add20e351d9cf115109164acbf1c64fa2cc5d004
    secrets:
      ADMIN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: stakater-user
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
    with:
      GOLANG_VERSION: ~1.23
      RUN_GOLANG_CI_LINT: false
      RUN_GOLANG_TESTS: true
      RELEASE_BRANCH: main
      OPERATOR_SDK_VERSION: v1.36.1